### ISSUE TITLE
Ideas for youtubevideo.js

### ISSUE THREAD

**Issue by SicorDev** [t3brightside/youtubevideo#1]
Hi, nice extension - thank you very much!

We had to replace $( with jQuery( in youtubevideo.js to make it work, maybe you want to change that in a future release as well.

We also moved the "small" CSS breakpoint from 600 to 400, as it's still looking good for us.

Maybe you can make the breakpoint location configurable. Or add a plugin option / constant to manually decide wether it should add "small" or not.

Greetings,
Manuel

**Comment by t3brightside** [comment]
Thanks for the feedback. Will take it under consideration, no conflict jQuery makes sense.
Breakpoint configuration in template constants makes sense.
For the next version I think I'll drop these things in.

**Comment by t3brightside** [comment]
Both features are available in the version 1.2.4 now!

**Comment by SicorDev** [comment]
Thank you very much!
