### ISSUE TITLE
Coverimage can't be added for non administrators

### ISSUE THREAD

**Issue by rtoenjes** [t3brightside/youtubevideo#12]
TYPO3 v9.5.27
youtubevideo v1.3.0 - 1.4.3

Although the tx_youtubevideo_coverimage has `'exclude' => 1` in `TCA/Overrides/tt_content.php` it does not appear to be allowed in `Backend user groups -> Page content`. So any non-admin can't add a coverimage in BE. Even if the user has got all access rights it does not appear to be added. Maybe it's because of the common fieldname „image“, don't know.

**Comment by t3brightside** [comment]
It uses tt_content.image field that is not possible to exclude by default in TYPO3.  Creating dedicated image field could be an option I guess.

**Comment by t3brightside** [comment]
@rtoenjes in dev now, coming with version 2.0.0, dedicated cover image field and upgrade wizard to migrate the images. Makes it possible to have full user rights control over the cover image field.
