### ISSUE TITLE
The package does not define an extension key in its composer.json

### ISSUE THREAD

**Issue by lexwebmaker** [t3brightside/youtubevideo#13]
The TYPO3 extension package "t3brightside/youtubevideo", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by t3brightside** [comment]
Added
