### ISSUE TITLE
Video is not shown

### ISSUE THREAD

**Issue by dr-brown** [t3brightside/youtubevideo#14]
Hello, 
after I press the button "Accept & Play" no video appears and the
browser console displays the following error:
![ye](https://user-images.githubusercontent.com/4175186/154085302-7f5352e8-ce76-4212-9406-79c8add85bca.jpg)

Browser: Firefox 93.0
TYPO3: 10.4.13
youtubevideo: 2.1.1

**Comment by t3brightside** [comment]
Hey @dr-brown !
I'm not able to reproduce the problem on Firefox 93 and TYPO3 11. At this moment not time to test on TYPO3 10.
Hard to tell anything by this information at this moment as haven't come across that problem before.
