### ISSUE TITLE
PHP Warnings in BE

### ISSUE THREAD

**Issue by rtoenjes** [t3brightside/youtubevideo#15]
TYPO3 11.5.13 composer
PHP 8.0.20
YoutubeVideo 2.1.1
PaginatedProcessors is not installed

After adding an video element in page module, there are four PHP Warnings:
`Core: Error handler (BE): PHP Warning: Undefined array key "tx_paginatedprocessors_paginationenabled" in /var/www/html/public/typo3conf/ext/youtubevideo/Classes/Hooks/PageLayoutView/YoutubevideoContentElementPreviewRenderer.php line 83`
`Core: Error handler (BE): PHP Warning: Undefined array key "tx_paginatedprocessors_itemsperpage" in /var/www/html/public/typo3conf/ext/youtubevideo/Classes/Hooks/PageLayoutView/YoutubevideoContentElementPreviewRenderer.php line 84`
`Core: Error handler (BE): PHP Warning: Undefined array key "tx_paginatedprocessors_pagelinksshown" in /var/www/html/public/typo3conf/ext/youtubevideo/Classes/Hooks/PageLayoutView/YoutubevideoContentElementPreviewRenderer.php line 85`
`Core: Error handler (BE): PHP Warning: Undefined array key "tx_paginatedprocessors_pagelinksshown" in /var/www/html/public/typo3conf/ext/youtubevideo/Classes/Hooks/PageLayoutView/YoutubevideoContentElementPreviewRenderer.php line 86`

**Comment by t3brightside** [comment]
Should be fixed in latest version now.
