### ISSUE TITLE
Backport 2.2.2 to 10.5

### ISSUE THREAD

**Issue by tylkomat** [t3brightside/youtubevideo#18]
Would it be a lot of effort to still allow Typo3 10.5 for the latest version as it's still in LTS until April 23?

**Comment by t3brightside** [comment]
Hey, thanks for the feedback. As the version introduces no new features or security fixes I don't really see the point in it.

**Comment by tylkomat** [comment]
Doesn't have to be 10.5 specifically, but 10.x in general as you dropped the support for 10.4 LTS with version 2.2.0, while it is still in LTS until April 23.

**Comment by t3brightside** [comment]
As said it's not bringing any new features or security fixes anyhow. So there is no real need for doing it. Besides who really needs it for some reason are open do do it themselves.

**Comment by tylkomat** [comment]
Are you willing to merge it if I provide a pull request?

**Comment by t3brightside** [comment]
Sorry, but unlikely so. To keep the code minimal for me means less to maintain in future. As it all comes out from my free time with no support what so ever it's how I manage to keep the amount of work going into it as low as possible. I'd encourage to upgrade the TYPO3 version.
