### ISSUE TITLE
danish translation

### ISSUE THREAD

**Issue by martin-git-kristensen** [t3brightside/youtubevideo#19]
I have created a translated da.locallang.xlf file in Resources/Private/Language - but it is still english language in frontend - see image.

I can edit the original locallang.xlf - but this i not the right way of translating.

What am I missing?

![billede](https://user-images.githubusercontent.com/54167636/221564512-e2b7d4bb-df3a-46c4-a51e-d827259ed27a.png)

**Comment by t3brightside** [comment]
Oh @martin-git-kristensen, thanks. There indeed seems to be an issue with translations, I'll try to have a look soon!

**Comment by t3brightside** [comment]
The translations should be fine with the latest versions.
