### ISSUE TITLE
lib.fluidContent -> lib.contentElement

### ISSUE THREAD

**Issue by stephangrass** [t3brightside/youtubevideo#2]
Please change

youtubevideo_pi1 =< lib.fluidContent to
youtubevideo_pi1 =< lib.contentElement

for TYPO3 > 8

"The TypoScript Object :typoscript:`lib.fluidContent` will be kept as copy of :typoscript:`lib.contentElement` for compatibility for the duration of TYPO3 v8 LTS and will be removed in TYPO3 v9."

**Comment by t3brightside** [comment]
Hey, thanks!
It's changed in latest master, next version will be released shortly.
