### ISSUE TITLE
TCA override removes the "Image Metadata" from tt_content images

### ISSUE THREAD

**Issue by Beltshassar** [t3brightside/youtubevideo#4]
The "Image Metadata" disappears from tt_content images when installing youtubevideo:1.3.0 on Typo3 9.5.5.
"Image Metadata" reappears when I downgrade to youtubevideo:1.2.4 or uninstall youtubevideo:1.3.0.

I suspect that the issue is inside 
youtubevideo/Configuration/TCA/Overrides/tt_content.php

**Comment by t3brightside** [comment]
Thank you Beltshassar, indeed seems to be problematic in non composer installs. I'll have a look at it...

**Comment by Beltshassar** [comment]
Hi @t3brightside - Sounds great! 
Btw. I'm having the issue with a composer installation. Let me know if you need any further details.

**Comment by t3brightside** [comment]
Indeed, it was a problem with all the older content types that use image field. It should be fixed in latest master now.

**Comment by Beltshassar** [comment]
Master is installed an everything seems to be in order.
Thankyou, that's great!
