### ISSUE TITLE
DSGVO/GDPR-Complience missing

### ISSUE THREAD

**Issue by mikeemike7** [t3brightside/youtubevideo#8]
It's the coolest youtube extension ever, but it doesn't seem to be DSGVO/GDPR compliant, so it's problematic to use the Ext in Europe. Google servers are already connected without, consent even when you include the static template without any video. Will there be a complient version soon?

**Comment by t3brightside** [comment]
Hey, thanks!
Unlikely there is to be one any time soon, but there's other extensions like sg_cookie_optin to cover that issue, can block iframes from loading before user consent. Not sure it plays well with the cover image function of the extension tho.
If "preconnect" is an issue it can be easily removed using a custom template.

**Comment by t3brightside** [comment]
@mikeemike7
Long time but there's a new alpha version available now in github and packagist, that addresses the problem. Still some time to new release but you're welcome to check it out.

**Comment by mikeemike7** [comment]
great news! Please keep going with this great extension!
